### ISSUE TITLE
Offline version of the AIA

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#121]
Some departments need to complete the AIA for secret systems. They consider their answers to the AIA to also be secret. They cannot use the online version.

For that requirement, it would be good to have a self-standing version that can be used offline (as a single HTML file or .zip archive). The requirements to run this should be as lightweight as possible (e.g. just requiring a browser).

**Why not Excel**
Previously, an Excel version of the AIA was developed and shared with departments with an offline requirement. Going forward, we'd like to maintain a single version of the AIA, and it should be the JS version (this). Maintaining a separate Excel (or Google Sheets) is a duplication of effort and risks not getting the same results.

**Why not Docker**
We need this simple, and not require much involvement of department's IT staff. Asking clients to run a Docker instance may be too much. It would require the participation of too many groups (IT security assessment, infrastructure, etc.) and cause delays in completing the AIA.

**Comment by gcharest** [comment]
So, might need a better use case scenario to flesh out this need.

The current implementation doesn't save any information whatsoever on any
servers. It's all within the person's browser.

Second thing, if really they have a need to run on internal network, I
really think that they have enough IT staff to do a local build on their
intranet. This can be simply deployed and maintained. Takes literally 5
minutes to configure and any "update" will take 2.

Outside of Docker, the app can also be ran with npm. That should be easier
for most I guess since Docker is indeed blocked in many departments.

We can discuss further "packaging options" but I'd recommend development
focus be towards maturing the impact assessment tool itself first.
Additional documentation is however critical for others.

We will however keep the issue open as there might be some way of
accommodating.

**Comment by gcharest** [comment]
Aye, also, why would they need to run an additional security assessment? It
was written in the open by GC employees, is self contained. Should work
with TBS Cyber to have those assessment done and available to all
departments.

**Comment by MrDeshaies** [comment]
Good point on the assessment. We need to keep in mind that secret stuff needs to happen on secret networks, which are generally airgapped (no internet access). npm without internet is doable but not trivial; been there...

@gcharest please touch base with @CalvinRodo , he seemed to have some thoughts on the subject.

I agree we can park this for now; not our top priority, but something to keep in mind.

**Comment by MrDeshaies** [comment]
This need seems to have vanished; closing.
