### ISSUE TITLE
Translations entered on results page missing from JSON

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#224]
On the results page, the user can enter translation for free-text elements entered during the questionnaire. After entering these translations, saving the JSON does not save the translations. They have to be re-entered.

**Comment by gcharest** [comment]
Hi! Just wondering if that's a feature request or if that's a bug?

As in: are the French text boxes supposed to be there at all? (I assume this is to support users in producing bilingual reports?)

**Comment by gcharest** [comment]
I've quickly looked at the behavior and although the content of French translation boxes (or English if you ran the survey in French) for the results are in the exported documents, there is no trigger to save it to the JSON file.

In order to update the JSON with the text boxes there would need to a "save the translation" function.

It's doable but then I'm wondering if it the most practical way of letting the users fill in bilingual assessment forms. Might have a look at saving the results content to an editable text-based document instead?

Or have people fill in the assessment in both official languages? Just trying to figure out best way forward to meet the need :grinning:

**Comment by MrDeshaies** [comment]
The French (or English) capture boxes on the result page are there to generate the bilingual PDF version which is downloadable at the bottom of the page. These bilingual docs are needed to publish the results on the open gov portal. See Issue #132 and Issue #133.

A button "save the translations" would work. I had hoped that the save button already present at the top of the result page (Issue #120) could play that role.

I see the JSON as the current work in progress. It should be able to persist any and all work done by the user so far, so that it can be loaded and resumed later. The "Save" button available throughout should serve the role of making the full json ready.

**Comment by MrDeshaies** [comment]
Not sure if this is useful, but it may be possible to use a [calculated value](https://surveyjs.io/Documentation/Library?id=LibraryOverview#calculatedvalues) to add the translation data to the surveyjs' json. The `expression` of the calculated value would call a [custom function](https://surveyjs.io/Documentation/Library?id=LibraryOverview#custom-functions) that would assemble the translation data. The JSON load would need to be modified to extract this data before it is re-calculated.

**Comment by Ancentury** [comment]
@MrDeshaies Thank you for your comments. I found in the results page, the section showing different from the Export at the bottom. E.g. Project Details is located in Section 3.1 under Section3, but in export section, it is located outside section3, at the beginning. Could you confirm if this is by design?

**Comment by MrDeshaies** [comment]
Yes, I confirm the ordering of project details is intended to be different between the results page, and the PDF.  When completing the AIA, the user wants to see his score and requirements; since he just completed the AIA, he knows the details of the project.  However, the PDF export is meant for a member of the public, who wants to understand details about the project (3.1) first; the score and impact level is a secondary consideration for members of the public.
