### ISSUE TITLE
Setup cache expiry time for app

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#72]
User has to clear cache or open up a "private session" in their browser to have the latest version available.

**Comment by CalvinRodo** [comment]
Since we are using github pages we'll have to setup some cache invalidation tricks to handle this https://ultimatecourses.com/blog/cache-busting-jekyll-github-pages

Github currently caches for 10 minutes which I don't think is that bad. 

Might just be easier to have people hold `ctrl+` click refresh or `ctrl+F5` (Chrome instructions only I'm sure you can google other ways to do this)

**Comment by MrDeshaies** [comment]
10 minutes on github pages is an acceptable compromise between caching efficiently and users getting new versions. Realistically, only developers wanting to see the version they've just pushed would be affected. The rest could wait 10 minutes.

N.B. this was also noticed for [open.canada.ca/aia](https://open.canada.ca/aia) (where cache was 10 years or so!) and they've changed the nginx cache headers to force the browser to check if a new version exists every time.

Closing.
